### ISSUE TITLE
集成PageHelper时候抛错

### ISSUE THREAD

**Issue by zhaofeng555** [chenlei2/spring-boot-mybatis-rw#16]
DataSourceProxy类中， 
method.invoke(((Map)ConnectionHold.CONNECTION_CONTEXT.get()).get(ConnectionHold.CURRENT_CONNECTION.get()), args);
这里抛错。
at com.github.pagehelper.PageHelper.getUrl(PageHelper.java:282) ~[pagehelper-4.1.1.jar:na]
	at com.github.pagehelper.PageHelper.getSqlUtil(PageHelper.java:305) ~[pagehelper-4.1.1.jar:na]
	at com.github.pagehelper.PageHelper.initSqlUtil(PageHelper.java:263) ~[pagehelper-4.1.1.jar:na]
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:250) ~[pagehelper-4.1.1.jar:na]

原因是：pageHelper 要依赖connection的DatabaseMetaData。 conn.getMetaData().getURL();
你后续会修复吗？

**Comment by chenlei2** [comment]
这个问题你解决了吗？ 可以提交代码我合并，如果你没有解决，我过一段时间看看，最近比较忙
